# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 20:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAccessDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.Database')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now=True)),
                ('querystring', models.TextField()),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.Database')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='databases',
            field=models.ManyToManyField(through='frontend.ProfileAccessDatabase', to='frontend.Database'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
