# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20160926_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graph',
            name='created_ts',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 26, 17, 47, 24, 275437, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
